package org.apache.cloudstack.api.command;

import com.cloud.event.EventTypes;
import com.cloud.exception.*;
import com.cloud.network.IpAddress;
import org.apache.cloudstack.acl.RoleType;
import org.apache.cloudstack.api.*;
import org.apache.cloudstack.api.response.CreateWireguardVpnResponse;
import org.apache.cloudstack.api.response.IPAddressResponse;
import org.apache.log4j.Logger;

@APICommand(name = "createWireguardVpn",
        description = "My API short description here",
        responseObject = CreateWireguardVpnResponse.class,
        since = "4.19.1.0",
        requestHasSensitiveInfo = true, responseHasSensitiveInfo = true,
        authorized = {RoleType.Admin, RoleType.ResourceAdmin, RoleType.DomainAdmin, RoleType.User})
public class CreateWireguardVpn extends BaseAsyncCreateCmd {

    public static final Logger s_logger = Logger.getLogger(CreateWireguardVpn.class.getName());

    /////////////////////////////////////////////////////
    //////////////// API parameters /////////////////////
    /////////////////////////////////////////////////////

    @Parameter(name = ApiConstants.PUBLIC_IP_ID,
            type = CommandType.UUID,
            entityType = IPAddressResponse.class,
            required = true,
            description = "public ip address id of the vpn server")
    private Long publicIpId;

    @Parameter(name = "peer_public_key",
            type = CommandType.STRING,
            required = true,
            description = "the public key of the user/remote device, if empty gets autogenerated")
    private String peerPublicKey;

    @Parameter(name = "iprange",
            type = CommandType.STRING,
            required = false,
            description = "the range of ip addresses to allocate to vpn clients. The first ip in the range will be taken by the vpn server")
    private String ipRange;

    @Parameter(name = ApiConstants.OPEN_FIREWALL,
            type = CommandType.BOOLEAN,
            description = "if true, firewall rule for source/end public port is automatically created; if false - firewall rule has to be created explicitly. Has value true by default")
    private Boolean openFirewall;

    /////////////////////////////////////////////////////
    /////////////////// Accessors ///////////////////////
    /////////////////////////////////////////////////////

    public Long getPublicIpId() {
        return publicIpId;
    }

    public String getIpRange() {
        return ipRange;
    }

    public Boolean getOpenFirewall() {
        return openFirewall;
    }

    @Override
    public long getEntityOwnerId() {
        IpAddress ip = _networkService.getIp(publicIpId);

        if (ip == null) {
            throw new InvalidParameterValueException("Unable to find ip address by id=" + publicIpId);
        }

        return ip.getAccountId();
    }

    @Override
    public String getEventDescription() {
        return "Create Remote Access VPN for account " + getEntityOwnerId() + " using public ip id=" + publicIpId;
    }

    @Override
    public String getEventType() {
        return EventTypes.EVENT_REMOTE_ACCESS_VPN_CREATE;
    }

    @Override
    public void create() throws ResourceAllocationException {

    }

    @Override
    public void execute() throws ResourceUnavailableException, InsufficientCapacityException, ServerApiException, ConcurrentOperationException, ResourceAllocationException, NetworkRuleConflictException {

    }
}
